### PR TITLE
Fix resize jump issue

### LINKED ISSUE #56: Bug on resize after having reached the bottom of the page
Hi there,

I've noticed a small bug if you resize the window after having reached the bottom of the page. The transform value seems to exceed the new instance limit.
It's getting back to a normal behavior after scrolling again.

To reproduce the bug, simply scroll to the bottom of the page and then resize the window: https://locomotivemtl.github.io/locomotive-scroll/

Tested on latests Chrome (v78) and Firefox (v70) on Windows.

I've fixed this issue by updating the updateScroll method so that the the instance delta y property can't exceed the instance limit and by then calling transform to reset the position in case it happens, however I've not dug deeply enough in the code to be sure it's not just a dirty hack:

```javascript
      key: "updateScroll",
      value: function updateScroll(e) {
        if (this.isScrolling || this.isDraggingScrollbar) {
          this.instance.scroll.y = lerp(this.instance.scroll.y, this.instance.delta.y, this.inertia * this.inertiaRatio);
        } else {
          // fix to avoid the limit to be exceeded on resize
          if(this.instance.delta.y > this.instance.limit) {
            this.instance.delta.y = this.instance.limit;
            // force transform to the max position (dirty hack?!)
            this.transform(this.el, this.instance.scroll.x, -this.instance.delta.y, 0);
          }
          this.instance.scroll.y = this.instance.delta.y;
        }
      }
```

(Edit: I was using v3.1.5, things may have changed by then)

Thank you very much folks for the awesome work!

### LINKED ISSUE #66: Body not resizing properly when smooth:true
Hello 👋

**Describe the bug**

On last version 3.2.5.

When smooth="true" , depending on the resize : bigger or smaller body will not adapt to the js-scroll container creating a white space under the page or cropping the footer. 

We've tried to force the resize to update the container with scroll.update(). We also copied the style from your demo (html, body & scroll container) without any good result. 

**To Reproduce**

You can see our issue [here](https://www.kairos-agency.com/demo/locomotive_issue/)

**Expected behavior**

Basically the same behavior as when smooth = "false"; 

**Desktop:**
-  Tested in Windows and OS
 - Chrome, Mozilla & Safari latest version.

We love LS thanks in advance for your help 👊

### PR DESCRIPTION
**Pull request by ajayns**
Fixes #56 and #66 

* Updates delta by ratio when the window resizes and forces scroll to calculated y.
* If delta exceeds limit, scrolls back to limit value.

[Live Demo](http://lsresize.surge.sh/)

### CODE REVIEW

**Comment by ajayns** [comment]
I was unsure if I should just commit the source changes or push the compiled files as well - so as of now, I've just pushed every change that was made including compiled files. Let me know if there needs to be any change here. @antoineboulanger @quentinhocde

**Comment by Jerek0** [comment]
Thank's for the contribution @ajayns ! We did some adjustments and merged 👍 

A few notes:
- We don't want to animate the scroll when it goes over the limit on resize, so we just set it instantly back inside the boundaries.
- Also, we don't want to use ratio of previous scroll to update new one accordingly on resize. The scroll stays at the same `y` coordinate as long as it's inside boundaries.
- We always `gulp build` and include compiled files when we commit

**Comment by ajayns** [comment]
Ahh, understood. I made some assumptions and moved forward with the changes so that I could get your input before I finalized it. 

And yes I did notice you commit the files but also had 2 commits, 1 being the change and another a version update with compiled files I believe - little confusing there. Maybe I could help with a little documentation too on dev and contributing?

**Comment by Jerek0** [comment]
>And yes I did notice you commit the files but also had 2 commits, 1 being the change and another a version update with compiled files I believe - little confusing there.

We always commit a new build with the new version name after our updates for more clarity, but we also build on every commit. Anyway it doesn't matter that much in PRs.

>Maybe I could help with a little documentation too on dev and contributing?

Feel free to add new PRs!

**Pull request merged**
