### PR TITLE
Add typescript types

### PR DESCRIPTION
**Pull request by raphcollective**
Bonjour/Hi people at Locomotive!

We're giving locomotive-scroll a try and noticed it was lacking Typescript support. Here's a PR to fix that, let me know if there's anything missing!

Also I deduced the types from reading the code but I might be wrong or imprecise on some parts so I would really appreciate if you could take the time to review and make sure that everything matches and is coherent.

Let me know if there's anything I can do to help!

### CODE REVIEW

**Comment by ammein** [comment]
This is so cool ! Hope this would be merge and deploy soon

**Comment by Jerek0** [comment]
Thank's for your contribution! 👍 

Unfortunately we don't plan to use nor to maintain a typescript version as we won't use it in our projects. That being said, we encourage you to maintain your fork and we can link it to our readme if you want.

**Comment by raphcollective** [comment]
Hi @Jerek0,

Thanks for the response,

I think I will submit the typings to the [DefinitelyTyped ](https://github.com/definitelytyped/definitelytyped) repo then, that way people won't have to use a fork to have the types. Once that's done a mention in the readme could be helpful for other fellow typescript users!

Also do you think it would be possible to have someone from you team have a look at the types when the new PR will be ready? Most of them are deduced from reading the code and I might have missed some parts.

**Comment by nicubarbaros** [comment]
Any change to have an official .d.ts file now? As typescript gets more and more popular

**Comment by jimvaneijk** [comment]
@Jerek0 I hope this you guys will rethink about this PR, typescript is really upcomming.

**Pull request closed without merging**
