### PR TITLE
Fixed issue with fixed elements lost their position while resizing wi…

### PR DESCRIPTION
**Pull request by mrlss**
Hello :)

After some research and debugging, i found, hopefully 😃 , a fix for issue with fixed elements on window `resize` event.

The main issue is that `data-scroll-sticky` blocks lost their position and `scroll-target` on window `resize`, after they become unfixed at the end of `scroll-target` block. 

With this small changes, i don't see this problem anymore on docs page.

Hope this will be merged ASAP, because this is known issue😗

Thanks for this great plugin 👊

### CODE REVIEW

**Comment by mrlss** [comment]
@thetoine hello :) It would be great if you could find some time to check this PR, and possible merge it 🙃

**Comment by thetoine** [comment]
@mrlss hello :) I'm not a maintainer on this project, I'm sure someone from Locomotive will review this PR in the near future.

**Comment by ebhoren** [comment]
@mrlss I think you should tag one on the maintainer of this project. Like @antoineboulanger or @quentinhocde.

Guys, please merge this fix 🙏

**Comment by panupatspyksw** [comment]
Hello I'm not sure it this already merge fixed this problem to the locomotivescroll package npm. I'm still face this problem, my problem it was when view resize my sticky header section was go up and if I scroll to top and make resize again it will be sticky at the same. right now I make my header snap back after resize when scroll through down it snap back to sticky but when scroll through up it not sticky. if someone can already fixed this problem can I see the structure of your code pls.

**Comment by dayneh88** [comment]
This bug is still present. I'm checking `src/scripts/smooth.js` and none of the updates from the supposed commit that fixed it, is present. Any updates on this? It's a pretty serious bug.

**Comment by JuchokJuk** [comment]
It fixed bug for me https://github.com/locomotivemtl/locomotive-scroll/issues/30#issuecomment-1080516548

**Pull request merged**
