### PR TITLE
v4

### PR DESCRIPTION
**Pull request by quentinhocde**
- Add horizontal scroll
- Update `scrollTo` parameters with `options` object
- Rewrite instance options to control desktop, tablet and mobile separately (more infos in the readme)
- Add `data-scroll-id=""` attribute to scope elements
- Add currents in-view elements as array in `on scroll` event
- Add progress value from 0 to 1, during the element is in the viewport. To play an animation for example.

**Update export:**

Now It's possible to import just the Native Class, if you don't need a smooth scroll.
As usual, you can do like this:
```
import LocomotiveScroll from 'locomotive-scroll';
```
Or just import the Native Class:
```
import { Native } from 'locomotive-scroll';
```
And create your instance like before
```
// const scroll = new LocomotiveScroll(options);
const scroll = new Native(options);
```

### CODE REVIEW

**Comment by glauber-sampaio** [comment]
Is anyone going to approve it? :)

**Comment by brunodeangelis** [comment]
Hi! It would be awesome if this PR was merged, I'm really in the need of using horizontal scrolling for a project I'm currently working on.

Thank you 😄

**Comment by oriolparicio** [comment]
There is a problem trying to scroll with the mouse over an iframe, the scroll stops working

**Comment by quentinhocde** [comment]
> There is a problem trying to scroll with the mouse over an iframe, the scroll stops working

@oriolparicio → https://github.com/locomotivemtl/locomotive-scroll/issues/19

**Pull request merged**
